const cds = require('@sap/cds');
const axios = require('axios');

module.exports = cds.service.impl(async function () {
    
    this.on('scheduleJob', async (req) => {
        try {
            // 1. Unpack the object generated by job-scheduler.js
            const frontendData = JSON.parse(req.data.payload);
            console.log(`📡 CAP Backend processing row: ${frontendData.description}`);
            
            let tokenUrl, clientId, clientSecret, apiBaseUrl;

            // 2. Load active BTP service instances
            if (process.env.VCAP_SERVICES) {
                const vcap = JSON.parse(process.env.VCAP_SERVICES);
                const jobSchedulerEnv = vcap.jobscheduler[0].credentials;
                
                apiBaseUrl = jobSchedulerEnv.url;
                tokenUrl = `${jobSchedulerEnv.uaa.url}/oauth/token`;
                clientId = jobSchedulerEnv.uaa.clientid;
                clientSecret = jobSchedulerEnv.uaa.clientsecret;
            } else {
                tokenUrl = "https://90b7867btrial.authentication.us10.hana.ondemand.com/oauth/token";
                clientId = "sb-3ffe0dd3-343c-43db-ab08-17eecdd9f2ba!b625063|sap-jobscheduler!b1";
                clientSecret = "0fc7383f-57d7-4be2-9c40-99cee21628fa$nME_zscOALQo2SKVVTaY29ygwCzRh3DZSWKo0aHQLxg=";
                apiBaseUrl = "https://jobscheduler-rest.cfapps.us10.hana.ondemand.com";
            }
            
            const subdomain = "90b7867btrial"; 
            const jobId = 7294864; 

            // 3. Fetch bearer token
            console.log(`🔑 Fetching active bearer token...`);
            const tokenParams = new URLSearchParams();
            tokenParams.append('grant_type', 'client_credentials');
            tokenParams.append('client_id', clientId);
            tokenParams.append('client_secret', clientSecret);

            const tokenResponse = await axios.post(tokenUrl, tokenParams, {
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
            });
            
            const accessToken = tokenResponse.data.access_token;
            console.log(`✅ Token issued successfully!`);

            // 4. Set the canonical BTP schedules API endpoint route
            const targetUrl = `${apiBaseUrl}/scheduler/jobs/${jobId}/schedules`;
            console.log(`🌐 Target Endpoint: ${targetUrl}`);

            // 5. MAP FRONTEND DATE/TIME STRAIGHT INTO THE BTP SCHEMA CONSTRAINTS
            // Extract the converted ISO date string created by your parseUtcDateTime method
            const dateObj = new Date(frontendData.startDate);
            const year = dateObj.getUTCFullYear();
            const month = String(dateObj.getUTCMonth() + 1).padStart(2, '0');
            const day = String(dateObj.getUTCDate()).padStart(2, '0');
            const hours = String(dateObj.getUTCHours()).padStart(2, '0');
            const minutes = String(dateObj.getUTCMinutes()).padStart(2, '0');
            const formattedTime = `${year}-${month}-${day} ${hours}:${minutes}`;

            const finalPayload = {
                description: frontendData.description || "Excel Scheduled Task",
                type: "one-time",                    // Keeps the core one-time flow alive
                time: formattedTime,                 // Formatted string: "YYYY-MM-DD HH:MM"
                timezone: "UTC",                     // Leverages the UTC flag from the front-end
                active: frontendData.enabled,        // Sets boolean true status
                data: JSON.stringify(frontendData.payload || {}) // Maps the nested Excel row data
            };

            console.log(`🚀 Dispatching structured payload parameters to BTP...`);
            const response = await axios.post(targetUrl, finalPayload, {
                headers: {
                    'Authorization': `Bearer ${accessToken}`,
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'x-sap-job-scheduler-tenant': subdomain
                }
            });

            console.log(`✅ Success response received from BTP Cloud!`);
            return JSON.stringify(response.data);

        } catch (error) {
            let errorDetails = error.message;
            if (error.response && error.response.data) {
                errorDetails = typeof error.response.data === 'object' 
                    ? JSON.stringify(error.response.data) 
                    : error.response.data;
            }
            console.error('🔴 Cloud Outbound Call Failed:', errorDetails);
            return req.error(500, `BTP Cloud Error: ${errorDetails}`);
        }
    });
});